-- Task & Project Management System — realistic development/test dataset
-- Runs after 01-init.sql (docker-entrypoint-initdb.d executes every .sql file
-- in this folder in filename order, against an empty data directory).
--
-- Purpose: a large, realistic dataset for exercising every feature end to
-- end (dashboard, team management, invitations, tasks, subtasks, comments,
-- notifications, data isolation) — not a minimal fixture set.
--
-- Architecture note: this schema has no separate `teams` table — a
-- `project` IS a team, and `project_members` (with its `status` column) IS
-- team membership/invitation. "8-12 teams" below is therefore the same
-- thing as "8-12 projects", not a separate concept layered on top.
--
-- password_hash below is a real bcrypt hash (cost 10, generated by this
-- app's own PasswordEncoder via POST /api/auth/register, then verified
-- against POST /api/auth/login) of the plaintext "DevPassword123!" — every
-- seeded user shares it. Development/test credentials only.

-- ==================== positions / departments ====================

INSERT INTO positions (name) VALUES
('System Administrator'), ('Product Manager'), ('Program Manager'), ('Engineering Manager'),
('Team Lead'), ('Senior Software Engineer'), ('Software Engineer'), ('UI/UX Designer'),
('QA Engineer'), ('DevOps Engineer'), ('Marketing Specialist'), ('HR Specialist'),
('Support Engineer');

INSERT INTO departments (name) VALUES
('IT Operations'), ('Product'), ('Engineering'), ('Design'), ('Quality Assurance'),
('Marketing'), ('Human Resources');

-- ==================== users ====================
-- 24 users: 1 Administrator, 3 Project Managers, 5 Team Leaders, 13 Team
-- Members (including one INACTIVE and one SUSPENDED for edge cases), plus
-- one brand-new "newuser" account attached to nothing at all.

INSERT INTO users (full_name, username, email, password_hash, gender, date_of_birth, phone_number, position_id, department_id, role_id, account_status) VALUES
('Alex Rivera',      'admin.system',     'admin.system@taskflow.dev',      '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1985-02-11', '+1-555-0201', (SELECT id FROM positions WHERE name = 'System Administrator'),    (SELECT id FROM departments WHERE name = 'IT Operations'),    (SELECT id FROM roles WHERE name = 'ADMINISTRATOR'),   'ACTIVE'),
('Olivia Bennett',   'pm.olivia',        'olivia.bennett@taskflow.dev',    '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1988-06-23', '+1-555-0202', (SELECT id FROM positions WHERE name = 'Product Manager'),          (SELECT id FROM departments WHERE name = 'Product'),          (SELECT id FROM roles WHERE name = 'PROJECT_MANAGER'), 'ACTIVE'),
('Marcus Delgado',   'pm.marcus',        'marcus.delgado@taskflow.dev',    '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1984-11-05', '+1-555-0203', (SELECT id FROM positions WHERE name = 'Program Manager'),          (SELECT id FROM departments WHERE name = 'Product'),          (SELECT id FROM roles WHERE name = 'PROJECT_MANAGER'), 'ACTIVE'),
('Priya Nathan',     'pm.priya',         'priya.nathan@taskflow.dev',      '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1990-03-30', '+1-555-0204', (SELECT id FROM positions WHERE name = 'Product Manager'),          (SELECT id FROM departments WHERE name = 'Product'),          (SELECT id FROM roles WHERE name = 'PROJECT_MANAGER'), 'ACTIVE'),
('Owen Fitzgerald',  'lead.owen',        'owen.fitzgerald@taskflow.dev',   '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1991-07-14', '+1-555-0205', (SELECT id FROM positions WHERE name = 'Engineering Manager'),      (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_LEADER'),     'ACTIVE'),
('Sara Kowalski',    'lead.sara',        'sara.kowalski@taskflow.dev',     '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1992-09-02', '+1-555-0206', (SELECT id FROM positions WHERE name = 'Team Lead'),                (SELECT id FROM departments WHERE name = 'Design'),           (SELECT id FROM roles WHERE name = 'TEAM_LEADER'),     'ACTIVE'),
('Victor Osei',      'lead.victor',      'victor.osei@taskflow.dev',       '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1989-12-19', '+1-555-0207', (SELECT id FROM positions WHERE name = 'Team Lead'),                (SELECT id FROM departments WHERE name = 'Quality Assurance'),(SELECT id FROM roles WHERE name = 'TEAM_LEADER'),     'ACTIVE'),
('Noah Whitfield',   'lead.noah',        'noah.whitfield@taskflow.dev',    '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1993-04-08', '+1-555-0208', (SELECT id FROM positions WHERE name = 'Team Lead'),                (SELECT id FROM departments WHERE name = 'Marketing'),        (SELECT id FROM roles WHERE name = 'TEAM_LEADER'),     'ACTIVE'),
('Amy Castellano',   'lead.amy',         'amy.castellano@taskflow.dev',    '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1990-01-27', '+1-555-0209', (SELECT id FROM positions WHERE name = 'Engineering Manager'),      (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_LEADER'),     'ACTIVE'),
('Chen Wu',          'dev.chen',         'chen.wu@taskflow.dev',           '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1994-05-16', '+1-555-0210', (SELECT id FROM positions WHERE name = 'Senior Software Engineer'), (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Raj Malhotra',     'dev.raj',          'raj.malhotra@taskflow.dev',      '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1995-08-21', '+1-555-0211', (SELECT id FROM positions WHERE name = 'Software Engineer'),        (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Mia Alvarez',      'dev.mia',          'mia.alvarez@taskflow.dev',       '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1996-02-03', '+1-555-0212', (SELECT id FROM positions WHERE name = 'Senior Software Engineer'), (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Tomas Novak',      'dev.tomas',        'tomas.novak@taskflow.dev',       '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1993-10-30', '+1-555-0213', (SELECT id FROM positions WHERE name = 'Software Engineer'),        (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Hana Suzuki',      'dev.hana',         'hana.suzuki@taskflow.dev',       '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1992-12-12', '+1-555-0214', (SELECT id FROM positions WHERE name = 'DevOps Engineer'),          (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Luna Petrova',     'design.luna',      'luna.petrova@taskflow.dev',      '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1995-03-19', '+1-555-0215', (SELECT id FROM positions WHERE name = 'UI/UX Designer'),           (SELECT id FROM departments WHERE name = 'Design'),           (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Kai Anderson',     'design.kai',       'kai.anderson@taskflow.dev',      '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1996-07-07', '+1-555-0216', (SELECT id FROM positions WHERE name = 'UI/UX Designer'),           (SELECT id FROM departments WHERE name = 'Design'),           (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Zoe Whitman',      'qa.zoe',           'zoe.whitman@taskflow.dev',       '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1994-11-24', '+1-555-0217', (SELECT id FROM positions WHERE name = 'QA Engineer'),              (SELECT id FROM departments WHERE name = 'Quality Assurance'),(SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Leo Marchetti',    'qa.leo',           'leo.marchetti@taskflow.dev',     '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1993-01-15', '+1-555-0218', (SELECT id FROM positions WHERE name = 'QA Engineer'),              (SELECT id FROM departments WHERE name = 'Quality Assurance'),(SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Grace Okafor',     'marketing.grace',  'grace.okafor@taskflow.dev',      '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1991-05-27', '+1-555-0219', (SELECT id FROM positions WHERE name = 'Marketing Specialist'),     (SELECT id FROM departments WHERE name = 'Marketing'),        (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Jonas Bergström',  'hr.jonas',         'jonas.bergstrom@taskflow.dev',   '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1987-09-09', '+1-555-0220', (SELECT id FROM positions WHERE name = 'HR Specialist'),            (SELECT id FROM departments WHERE name = 'Human Resources'),  (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
('Ivy Sandoval',     'support.ivy',      'ivy.sandoval@taskflow.dev',      '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Female', '1995-06-06', '+1-555-0221', (SELECT id FROM positions WHERE name = 'Support Engineer'),         (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'ACTIVE'),
-- Edge-case accounts: a contractor whose account went INACTIVE and a former
-- employee who was SUSPENDED, each still a nominal project_members row (see
-- below) but excluded from task assignment by the check_assignee_not_suspended
-- trigger — same pattern the original demo data used for this rule.
('Felix Guerrero',   'contractor.felix', 'felix.guerrero@taskflow.dev',    '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1990-08-18', '+1-555-0222', (SELECT id FROM positions WHERE name = 'Software Engineer'),        (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'INACTIVE'),
('Diego Fuentes',    'exemployee.diego', 'diego.fuentes@taskflow.dev',     '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', 'Male',   '1988-04-04', '+1-555-0223', (SELECT id FROM positions WHERE name = 'Software Engineer'),        (SELECT id FROM departments WHERE name = 'Engineering'),      (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'),     'SUSPENDED'),
-- The "brand-new registration" test account: no position/department, no
-- project_members row anywhere below — must show up completely empty
-- (0 teams/projects/tasks/subtasks/comments) everywhere in the app.
('New User',         'newuser',          'newuser@taskflow.dev',           '$2a$10$ES.bYeqN/GnbYn/Wgz8lp.L8flAurU4A7HiwnEmRFh604OXZxsb2G', NULL,     NULL,         NULL,          NULL, NULL, (SELECT id FROM roles WHERE name = 'TEAM_MEMBER'), 'ACTIVE');

-- ==================== projects ("teams") ====================
-- No separate `teams` table exists in this schema — a project IS a team,
-- and its project_members rows are that team's membership. Dates are
-- CURRENT_DATE-relative so this file stays valid whenever it's actually run.
-- progress is intentionally omitted (defaults to 0) — fully derived from
-- task completion by a DB trigger, and self-corrects as tasks are seeded.

INSERT INTO projects (project_code, name, description, start_date, end_date, manager_id, priority, status) VALUES
('PRJ-2001', 'Website Redesign',            'Public marketing site redesign and rebrand',            CURRENT_DATE - 75,  CURRENT_DATE + 75,  (SELECT id FROM users WHERE username = 'pm.olivia'), 'HIGH',     'IN_PROGRESS'),
('PRJ-2002', 'Mobile Banking App',          'Native mobile banking experience, phase 2',              CURRENT_DATE - 135, CURRENT_DATE + 140, (SELECT id FROM users WHERE username = 'pm.marcus'), 'CRITICAL', 'IN_PROGRESS'),
('PRJ-2003', 'Core API Migration',          'Migrate the core platform API to v2',                    CURRENT_DATE - 165, CURRENT_DATE + 30,  (SELECT id FROM users WHERE username = 'pm.olivia'), 'HIGH',     'IN_PROGRESS'),
('PRJ-2004', 'Design System 2.0',           'Unify UI components across every product surface',       CURRENT_DATE - 10,  CURRENT_DATE + 120, (SELECT id FROM users WHERE username = 'pm.priya'),  'MEDIUM',   'PLANNING'),
('PRJ-2005', 'Internal Analytics Dashboard','Internal reporting and operations tooling',              CURRENT_DATE - 90,  CURRENT_DATE + 80,  (SELECT id FROM users WHERE username = 'pm.marcus'), 'MEDIUM',   'IN_PROGRESS'),
('PRJ-2006', 'Customer Support Portal',     'Self-service support portal for customers',              CURRENT_DATE - 195, CURRENT_DATE + 45,  (SELECT id FROM users WHERE username = 'pm.priya'),  'LOW',      'ON_HOLD'),
('PRJ-2007', 'Q4 Marketing Campaign',       'End-of-year multi-channel marketing push',               CURRENT_DATE + 5,   CURRENT_DATE + 95,  (SELECT id FROM users WHERE username = 'pm.olivia'), 'HIGH',     'PLANNING'),
('PRJ-2008', 'Social Media Platform Revamp','Refresh brand presence across social channels',          CURRENT_DATE - 45,  CURRENT_DATE + 165, (SELECT id FROM users WHERE username = 'pm.priya'),  'MEDIUM',   'IN_PROGRESS'),
('PRJ-2009', 'HR Onboarding Portal',        'Self-service onboarding flow for new hires',             CURRENT_DATE - 240, CURRENT_DATE - 75,  (SELECT id FROM users WHERE username = 'pm.marcus'), 'LOW',      'COMPLETED'),
('PRJ-2010', 'Data Warehouse Upgrade',      'Move the analytics warehouse onto the new pipeline',     CURRENT_DATE - 315, CURRENT_DATE + 75,  (SELECT id FROM users WHERE username = 'pm.olivia'), 'HIGH',     'IN_PROGRESS');

-- ==================== project_members (ACTIVE — real team membership) ====================
-- "Team A" (PRJ-2001) and "Team B" (PRJ-2009) below share NO users at all —
-- kept deliberately disjoint to make cross-team data-isolation easy to test.

INSERT INTO project_members (project_id, user_id, project_role) VALUES
-- PRJ-2001 Website Redesign — "Team A" (isolation test set)
((SELECT id FROM projects WHERE project_code = 'PRJ-2001'), (SELECT id FROM users WHERE username = 'pm.olivia'),   'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2001'), (SELECT id FROM users WHERE username = 'lead.owen'),   'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2001'), (SELECT id FROM users WHERE username = 'dev.chen'),    'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2001'), (SELECT id FROM users WHERE username = 'dev.mia'),     'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2001'), (SELECT id FROM users WHERE username = 'design.luna'),'TEAM_MEMBER'),

-- PRJ-2002 Mobile Banking App
((SELECT id FROM projects WHERE project_code = 'PRJ-2002'), (SELECT id FROM users WHERE username = 'pm.marcus'),        'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2002'), (SELECT id FROM users WHERE username = 'lead.owen'),        'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2002'), (SELECT id FROM users WHERE username = 'dev.raj'),          'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2002'), (SELECT id FROM users WHERE username = 'dev.tomas'),        'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2002'), (SELECT id FROM users WHERE username = 'qa.zoe'),           'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2002'), (SELECT id FROM users WHERE username = 'dev.hana'),         'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2002'), (SELECT id FROM users WHERE username = 'exemployee.diego'),'TEAM_MEMBER'),

-- PRJ-2003 Core API Migration
((SELECT id FROM projects WHERE project_code = 'PRJ-2003'), (SELECT id FROM users WHERE username = 'pm.olivia'),  'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2003'), (SELECT id FROM users WHERE username = 'lead.amy'),   'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2003'), (SELECT id FROM users WHERE username = 'dev.raj'),    'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2003'), (SELECT id FROM users WHERE username = 'dev.hana'),   'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2003'), (SELECT id FROM users WHERE username = 'support.ivy'),'TEAM_MEMBER'),

-- PRJ-2004 Design System 2.0
((SELECT id FROM projects WHERE project_code = 'PRJ-2004'), (SELECT id FROM users WHERE username = 'pm.priya'),   'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2004'), (SELECT id FROM users WHERE username = 'lead.sara'),  'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2004'), (SELECT id FROM users WHERE username = 'design.luna'),'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2004'), (SELECT id FROM users WHERE username = 'design.kai'), 'TEAM_MEMBER'),

-- PRJ-2005 Internal Analytics Dashboard
((SELECT id FROM projects WHERE project_code = 'PRJ-2005'), (SELECT id FROM users WHERE username = 'pm.marcus'),        'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2005'), (SELECT id FROM users WHERE username = 'lead.amy'),         'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2005'), (SELECT id FROM users WHERE username = 'dev.chen'),         'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2005'), (SELECT id FROM users WHERE username = 'dev.tomas'),        'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2005'), (SELECT id FROM users WHERE username = 'contractor.felix'),'TEAM_MEMBER'),

-- PRJ-2006 Customer Support Portal
((SELECT id FROM projects WHERE project_code = 'PRJ-2006'), (SELECT id FROM users WHERE username = 'pm.priya'),   'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2006'), (SELECT id FROM users WHERE username = 'lead.victor'),'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2006'), (SELECT id FROM users WHERE username = 'qa.leo'),     'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2006'), (SELECT id FROM users WHERE username = 'support.ivy'),'TEAM_MEMBER'),

-- PRJ-2007 Q4 Marketing Campaign
((SELECT id FROM projects WHERE project_code = 'PRJ-2007'), (SELECT id FROM users WHERE username = 'pm.olivia'),      'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2007'), (SELECT id FROM users WHERE username = 'lead.noah'),      'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2007'), (SELECT id FROM users WHERE username = 'marketing.grace'),'TEAM_MEMBER'),

-- PRJ-2008 Social Media Platform Revamp
((SELECT id FROM projects WHERE project_code = 'PRJ-2008'), (SELECT id FROM users WHERE username = 'pm.priya'),       'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2008'), (SELECT id FROM users WHERE username = 'lead.noah'),      'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2008'), (SELECT id FROM users WHERE username = 'marketing.grace'),'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2008'), (SELECT id FROM users WHERE username = 'design.kai'),     'TEAM_MEMBER'),

-- PRJ-2009 HR Onboarding Portal — "Team B" (isolation test set, disjoint from Team A)
((SELECT id FROM projects WHERE project_code = 'PRJ-2009'), (SELECT id FROM users WHERE username = 'pm.marcus'), 'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2009'), (SELECT id FROM users WHERE username = 'hr.jonas'),  'TEAM_MEMBER'),

-- PRJ-2010 Data Warehouse Upgrade
((SELECT id FROM projects WHERE project_code = 'PRJ-2010'), (SELECT id FROM users WHERE username = 'pm.olivia'),'PROJECT_MANAGER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2010'), (SELECT id FROM users WHERE username = 'lead.amy'), 'TEAM_LEADER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2010'), (SELECT id FROM users WHERE username = 'dev.hana'), 'TEAM_MEMBER'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2010'), (SELECT id FROM users WHERE username = 'qa.zoe'),   'TEAM_MEMBER');

-- ==================== team invitations (PENDING / DECLINED) ====================
-- Real project_members rows with status != ACTIVE — no membership is
-- granted by these (findProjectIdsByUserId and the assignee-eligibility
-- trigger both filter to status='ACTIVE'), matching the app's actual
-- invite/accept/decline workflow.

INSERT INTO project_members (project_id, user_id, project_role, status, invited_by) VALUES
((SELECT id FROM projects WHERE project_code = 'PRJ-2001'), (SELECT id FROM users WHERE username = 'dev.tomas'),      'TEAM_MEMBER', 'PENDING', (SELECT id FROM users WHERE username = 'pm.olivia')),
((SELECT id FROM projects WHERE project_code = 'PRJ-2002'), (SELECT id FROM users WHERE username = 'qa.leo'),         'TEAM_MEMBER', 'PENDING', (SELECT id FROM users WHERE username = 'pm.marcus')),
((SELECT id FROM projects WHERE project_code = 'PRJ-2004'), (SELECT id FROM users WHERE username = 'dev.chen'),       'TEAM_MEMBER', 'PENDING', (SELECT id FROM users WHERE username = 'pm.priya')),
((SELECT id FROM projects WHERE project_code = 'PRJ-2006'), (SELECT id FROM users WHERE username = 'dev.mia'),        'TEAM_MEMBER', 'PENDING', (SELECT id FROM users WHERE username = 'pm.priya')),
((SELECT id FROM projects WHERE project_code = 'PRJ-2010'), (SELECT id FROM users WHERE username = 'marketing.grace'),'TEAM_MEMBER', 'PENDING', (SELECT id FROM users WHERE username = 'pm.olivia'));

INSERT INTO project_members (project_id, user_id, project_role, status, invited_by, responded_at) VALUES
((SELECT id FROM projects WHERE project_code = 'PRJ-2005'), (SELECT id FROM users WHERE username = 'qa.leo'),   'TEAM_MEMBER', 'DECLINED', (SELECT id FROM users WHERE username = 'pm.marcus'), now() - interval '2 days'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2007'), (SELECT id FROM users WHERE username = 'hr.jonas'), 'TEAM_MEMBER', 'DECLINED', (SELECT id FROM users WHERE username = 'pm.olivia'), now() - interval '5 days'),
((SELECT id FROM projects WHERE project_code = 'PRJ-2008'), (SELECT id FROM users WHERE username = 'dev.raj'), 'TEAM_MEMBER', 'DECLINED', (SELECT id FROM users WHERE username = 'pm.priya'),  now() - interval '1 day');

INSERT INTO notifications (user_id, type, title, message, project_id, is_read) VALUES
((SELECT id FROM users WHERE username = 'dev.tomas'),      'TEAM_INVITATION', 'Team invitation', 'Olivia Bennett invited you to join "Website Redesign"',            (SELECT id FROM projects WHERE project_code = 'PRJ-2001'), false),
((SELECT id FROM users WHERE username = 'qa.leo'),          'TEAM_INVITATION', 'Team invitation', 'Marcus Delgado invited you to join "Mobile Banking App"',          (SELECT id FROM projects WHERE project_code = 'PRJ-2002'), false),
((SELECT id FROM users WHERE username = 'dev.chen'),        'TEAM_INVITATION', 'Team invitation', 'Priya Nathan invited you to join "Design System 2.0"',             (SELECT id FROM projects WHERE project_code = 'PRJ-2004'), false),
((SELECT id FROM users WHERE username = 'dev.mia'),         'TEAM_INVITATION', 'Team invitation', 'Priya Nathan invited you to join "Customer Support Portal"',       (SELECT id FROM projects WHERE project_code = 'PRJ-2006'), false),
((SELECT id FROM users WHERE username = 'marketing.grace'), 'TEAM_INVITATION', 'Team invitation', 'Olivia Bennett invited you to join "Data Warehouse Upgrade"',      (SELECT id FROM projects WHERE project_code = 'PRJ-2010'), false),
((SELECT id FROM users WHERE username = 'pm.marcus'), 'TEAM_INVITATION_RESPONDED', 'Invitation declined', 'Leo Marchetti declined your invitation to join "Internal Analytics Dashboard"', (SELECT id FROM projects WHERE project_code = 'PRJ-2005'), true),
((SELECT id FROM users WHERE username = 'pm.olivia'), 'TEAM_INVITATION_RESPONDED', 'Invitation declined', 'Jonas Bergström declined your invitation to join "Q4 Marketing Campaign"',       (SELECT id FROM projects WHERE project_code = 'PRJ-2007'), true),
((SELECT id FROM users WHERE username = 'pm.priya'),  'TEAM_INVITATION_RESPONDED', 'Invitation declined', 'Raj Malhotra declined your invitation to join "Social Media Platform Revamp"',   (SELECT id FROM projects WHERE project_code = 'PRJ-2008'), true);

-- ==================== tasks / task_assignees / subtasks / comments ====================
-- Procedural on purpose: at this volume (70 tasks x subtasks/comments/
-- assignees), generating each row from the actual per-project ACTIVE
-- membership is far more reliable than hand-writing every FK, and
-- guarantees every business rule is respected by construction:
--   - task.due_date is always derived from its own project's [start,end]
--     range, so check_task_due_date_within_project can never fail.
--   - task_assignees only ever draws from that task's own project's ACTIVE
--     members whose account_status is ACTIVE, so
--     check_assignee_is_project_member / check_assignee_not_suspended can
--     never fail (this is exactly why Felix/Diego above are excluded here
--     even though they're nominal project_members).
--   - subtasks/comments always belong to a task that was just created in
--     the same loop.
DO $$
DECLARE
    proj RECORD;
    task_id BIGINT;
    task_title_suffixes TEXT[] := ARRAY[
        'Kickoff and requirements planning',
        'Design and requirements review',
        'Core feature implementation',
        'Integration and API wiring',
        'QA regression pass',
        'Fix reported defects',
        'Documentation and handoff'
    ];
    base_statuses TEXT[] := ARRAY['TO_DO','IN_PROGRESS','IN_PROGRESS','IN_REVIEW','COMPLETED','IN_PROGRESS','TO_DO'];
    base_priorities TEXT[] := ARRAY['LOW','MEDIUM','HIGH','MEDIUM','HIGH','URGENT','LOW'];
    i INT;
    final_status TEXT;
    member_ids BIGINT[];
    creator_id BIGINT;
    assignee_id BIGINT;
    total_days INT;
    t_start DATE;
    t_due DATE;
    t_progress NUMERIC;
    subtask_titles TEXT[] := ARRAY[
        'Draft initial version', 'Get peer review', 'Write unit tests', 'Update documentation',
        'Verify on staging', 'Address review comments', 'Final polish', 'Set up test data'
    ];
    comment_pool TEXT[] := ARRAY[
        'Backend endpoint is ready for review.',
        'I''ve finished the UI for this, please take a look.',
        'Can you review this when you get a chance?',
        'This is blocked by the authentication issue on the API side.',
        'Fixed in the latest commit, ready for re-test.',
        'Good catch, updating now.',
        'Tested locally, works as expected.',
        'Let''s sync tomorrow to unblock this.',
        'Pushed a fix, please verify.',
        'Looks good, merging shortly.',
        'Ran into an edge case with empty input, investigating.',
        'Nice work on this one!'
    ];
    n_subtasks INT;
    n_comments INT;
    j INT;
    parent_cid BIGINT;
    new_cid BIGINT;
    author_id BIGINT;
BEGIN
    FOR proj IN SELECT id, name, status AS proj_status, start_date, end_date, manager_id FROM projects ORDER BY id LOOP
        -- Only ACTIVE project_members whose account itself is ACTIVE — this
        -- is the exact pool the DB triggers allow for task_assignees.
        SELECT array_agg(pm.user_id) INTO member_ids
        FROM project_members pm JOIN users u ON u.id = pm.user_id
        WHERE pm.project_id = proj.id AND pm.status = 'ACTIVE' AND u.account_status = 'ACTIVE';

        creator_id := proj.manager_id;
        total_days := GREATEST(proj.end_date - proj.start_date, 7);

        FOR i IN 1..7 LOOP
            t_start := proj.start_date + floor(total_days * (i - 1) / 8.0)::int;
            t_due   := proj.start_date + floor(total_days * i / 8.0)::int;
            IF t_due <= t_start THEN t_due := t_start + 3; END IF;
            IF t_due > proj.end_date THEN t_due := proj.end_date; END IF;

            final_status := base_statuses[i];
            IF proj.proj_status = 'PLANNING' THEN
                final_status := 'TO_DO';
            ELSIF proj.proj_status = 'COMPLETED' THEN
                final_status := CASE WHEN i = 6 THEN 'CANCELLED' ELSE 'COMPLETED' END;
            END IF;

            t_progress := CASE final_status
                WHEN 'COMPLETED' THEN 100
                WHEN 'CANCELLED' THEN 0
                WHEN 'IN_REVIEW' THEN 85
                WHEN 'IN_PROGRESS' THEN 25 + floor(random() * 50)
                ELSE 0
            END;

            INSERT INTO tasks (project_id, title, description, priority, status, start_date, due_date, estimated_hours, progress, created_by)
            VALUES (
                proj.id,
                task_title_suffixes[i] || ' — ' || proj.name,
                'Seed task for ' || proj.name || ': ' || lower(task_title_suffixes[i]) || '.',
                base_priorities[i],
                final_status,
                t_start, t_due,
                (4 + floor(random() * 20))::numeric,
                t_progress,
                creator_id
            ) RETURNING id INTO task_id;

            IF member_ids IS NOT NULL AND array_length(member_ids, 1) > 0 AND i NOT IN (1, 7) THEN
                assignee_id := member_ids[1 + floor(random() * array_length(member_ids, 1))::int];
                INSERT INTO task_assignees (task_id, user_id) VALUES (task_id, assignee_id) ON CONFLICT DO NOTHING;
                IF i = 3 AND array_length(member_ids, 1) > 1 THEN
                    assignee_id := member_ids[1 + floor(random() * array_length(member_ids, 1))::int];
                    INSERT INTO task_assignees (task_id, user_id) VALUES (task_id, assignee_id) ON CONFLICT DO NOTHING;
                END IF;
            END IF;

            n_subtasks := 1 + floor(random() * 3)::int;
            FOR j IN 1..n_subtasks LOOP
                INSERT INTO subtasks (task_id, title, assignee_id, due_date, status)
                VALUES (
                    task_id,
                    subtask_titles[1 + floor(random() * array_length(subtask_titles, 1))::int],
                    CASE WHEN member_ids IS NOT NULL AND array_length(member_ids, 1) > 0 AND random() > 0.3
                         THEN member_ids[1 + floor(random() * array_length(member_ids, 1))::int] ELSE NULL END,
                    t_due - floor(random() * 5)::int,
                    (ARRAY['TO_DO', 'IN_PROGRESS', 'COMPLETED'])[1 + floor(random() * 3)::int]
                );
            END LOOP;

            IF member_ids IS NOT NULL AND array_length(member_ids, 1) > 0 THEN
                n_comments := 1 + floor(random() * 3)::int;
                parent_cid := NULL;
                FOR j IN 1..n_comments LOOP
                    author_id := member_ids[1 + floor(random() * array_length(member_ids, 1))::int];
                    INSERT INTO comments (task_id, user_id, parent_comment_id, message)
                    VALUES (
                        task_id, author_id,
                        CASE WHEN j > 1 AND random() > 0.5 THEN parent_cid ELSE NULL END,
                        comment_pool[1 + floor(random() * array_length(comment_pool, 1))::int]
                    ) RETURNING id INTO new_cid;
                    parent_cid := new_cid;
                END LOOP;
            END IF;
        END LOOP;
    END LOOP;
END $$;

-- Force a handful of genuinely overdue tasks (due in the past, not
-- completed) for testing the overdue-detection view/notifications — only
-- within projects whose own end_date is safely still in the future, so
-- check_task_due_date_within_project can never fail.
WITH candidates AS (
    SELECT t.id FROM tasks t JOIN projects p ON p.id = t.project_id
    WHERE p.status IN ('IN_PROGRESS', 'ON_HOLD') AND p.end_date >= CURRENT_DATE + 5
    ORDER BY t.id
    LIMIT 8
)
UPDATE tasks SET
    due_date = CURRENT_DATE - (2 + floor(random() * 8))::int,
    start_date = LEAST(start_date, CURRENT_DATE - 20),
    status = 'IN_PROGRESS',
    progress = 30 + floor(random() * 40)
WHERE id IN (SELECT id FROM candidates);

-- ==================== notifications derived from tasks/assignments ====================

INSERT INTO notifications (user_id, type, title, message, project_id, task_id, is_read)
SELECT ta.user_id, 'TASK_ASSIGNED', 'New task assigned',
       'You were assigned to "' || t.title || '"',
       t.project_id, t.id,
       (random() > 0.4)
FROM task_assignees ta JOIN tasks t ON t.id = ta.task_id;

INSERT INTO notifications (user_id, type, title, message, project_id, task_id, is_read)
SELECT ta.user_id, 'TASK_STATUS_CHANGED', 'Task status updated',
       '"' || t.title || '" is now ' || t.status,
       t.project_id, t.id,
       (random() > 0.5)
FROM task_assignees ta JOIN tasks t ON t.id = ta.task_id
WHERE t.status <> 'TO_DO';

-- Reuses the existing DB function rather than hand-inserting OVERDUE_TASK
-- rows — generates one per (assignee, overdue task) not already notified
-- today, for the tasks the UPDATE above just created.
SELECT fn_generate_overdue_notifications();
